import pandas as pd

In [7]:
resume = pd.read_csv("1 resume .csv")

In [8]:
resume

    Name                                    Resume
0  Rahul  Python SQL Machine Learning Pandas Excel
1  Priya                  Java Spring SQL HTML CSS
2  Arjun               Python Data Analysis Pandas
3   Neha             HTML CSS JavaScript Bootstrap
4  Kiran        Python SQL Pandas Machine Learning

In [9]:
with open("job_description.txt","r") as file:
    job = file.read()

print(job)

Python Developer

Required Skills:

Python
SQL
Machine Learning
Pandas

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
texts = [job] + resume["Resume"].tolist()

vectorizer = TfidfVectorizer()

matrix = vectorizer.fit_transform(texts)

In [12]:
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
scores = cosine_similarity(matrix[0:1], matrix[1:]).flatten()

resume["Score"] = scores

In [14]:
resume = resume.sort_values(by="Score", ascending=False)

resume

    Name                                    Resume     Score
4  Kiran        Python SQL Pandas Machine Learning  0.676715
0  Rahul  Python SQL Machine Learning Pandas Excel  0.553198
2  Arjun               Python Data Analysis Pandas  0.260620
1  Priya                  Java Spring SQL HTML CSS  0.074297
3   Neha             HTML CSS JavaScript Bootstrap  0.000000

In [15]:
job_skills = ["python","sql","machine learning","pandas"]

In [16]:
def missing_skills(text):

    text = text.lower()

    missing = []

    for skill in job_skills:
        if skill not in text:
            missing.append(skill)

    return missing

In [17]:
resume["Missing Skills"] = resume["Resume"].apply(missing_skills)

In [18]:
print (resume)

    Name                                    Resume     Score  \
4  Kiran        Python SQL Pandas Machine Learning  0.676715
0  Rahul  Python SQL Machine Learning Pandas Excel  0.553198
2  Arjun               Python Data Analysis Pandas  0.260620
1  Priya                  Java Spring SQL HTML CSS  0.074297
3   Neha             HTML CSS JavaScript Bootstrap  0.000000

                            Missing Skills
4                                       []
0                                       []
2                  [sql, machine learning]
1       [python, machine learning, pandas]
3  [python, sql, machine learning, pandas]